### ISSUE TITLE
系统因未找到配置文件而无法开机自启

### ISSUE THREAD

**Issue by cxdluckly** [LS-KR/DesktopDynamic#1]
您好，我在我的电脑上部署了您的程序。
在设置程序开机自启后，程序无法自启并会如下弹出提示：
`Cannot Found Config and Source File!`
我打印了日志，发现我的电脑上程序找到的根目录为
`C:\Windows\SysWOW64\`
在上面的路径中肯定是没有`【config.ini】`文件的。
解决方法：
在读取`【config.ini】`文件我使用了下面的方法，程序可正常自启动。
`File.ReadAllLines(System.Windows.Forms.Application.StartupPath + "\\" + "config.ini")`
希望您可以知晓！

**Comment by LS-KR** [comment]
已修复
